sampleapp/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views

from . import views

app_name = 'sampleapp'

# Basics
urlpatterns = [
    url(r'^$', views.index_view, name='index'),
    url(r'^about/$', views.about_view, name='about'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
]

# Create an account
urlpatterns += [
    url(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^signup/$', views.signup_view, name='signup'),
]

# Existing account operations
urlpatterns += [
    url(r'^change/$', views.change_pwd, name='change_pwd'),
    url(r'^home/$', views.home_view, name='home'),
    url(r'^profile/$', views.profile_view, name='profile'),
    url(r'^error/$', views.error_view, name='error'),
]

# Authentication operations
urlpatterns += [
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    # url(r'^login/$', auth_views.login, name='login'),
    # url(r'^logout/$', auth_views.logout, name='logout'),
]

# Chat operations
urlpatterns += [
    url(r'^chat/(?P<u>[a-zA-Z0-9_]+)/$', views.chat_with, name='chat'),
]

# LOGIN_URL = 'signin'
# LOGOUT_URL = 'logout'
# LOGIN_REDIRECT_URL = 'home'

website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

from sampleapp import views as sampleapp_views

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/music/')),
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('sampleapp.urls')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    # url(r'^oauth/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    # url(r'^accounts/login/$', sampleapp_views.signin_view),
]

LOGIN_URL = 'login'
LOGOUT_URL = 'logout'
LOGIN_REDIRECT_URL = '/music/home'

sampleapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from datetime import datetime

from django.contrib.auth.models import User
from django.db import models
from django.db.models.deletion import CASCADE, DO_NOTHING

# Create your models here.
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email_confirmed = models.BooleanField(default=False)
    # slug = models.SlugField(default=False, null=True)


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()


# Database model for Chat Room
class Room(models.Model):
    name = models.TextField()
    label = models.SlugField(unique=True)

    def contains_user(self, id):
        if self.label == 'global':
            try:
                uname = User.objects.get(id=id)
                my_msgs = self.messages.filter(sender__username__iexact=uname.username)
                if my_msgs:
                    return True
                else:
                    return False
            except User.DoesNotExist:
                return False

        one, other = self.label.split('_')
        return str(one) == str(id) or str(other) == str(id)

    def get_room_name(self, user_id):
        """
        Returns the room name, usually the name of the other person.
        :return: Name
        """
        if self.label == 'global':
            return 'Global'

        other = self.get_other_participant(user_id)
        other_obj = User.objects.get(id=other)

        if len(other_obj.first_name) != 0 and len(other_obj.last_name) != 0:
            return other_obj.first_name + ' ' + other_obj.last_name
        else:
            return other_obj.username

    def get_other_participant(self, user_id):
        """
        Returns the other participant in the chat.
        It is assumed that the user_id is a number.
        :param user_id:
        :return:
        """
        one, other = self.label.split('_')
        one = str(one)
        other = str(other)
        user_id = str(user_id)

        if one == user_id:
            return other

        return one

    def get_room_link(self, user_id):
        """
        Returns the "room link". This basically means the method returns either the string 'all',
        or the ID of the other participant.
        :param user_id:
        :return:
        """

        if self.label == 'global':
            return 'all'

        return self.get_other_participant(user_id)


# Database model for Chat Message
class Message(models.Model):
    room = models.ForeignKey(Room, related_name='messages', on_delete=DO_NOTHING)
    sender = models.ForeignKey(User, related_name='sent_messages', on_delete=CASCADE, null=True)
    message = models.TextField()
    timestamp = models.DateTimeField(default=datetime.now(), db_index=True)


# Database model for one User's music collection
class MusicPiece(models.Model):
    creator = models.ForeignKey(User, related_name='my_music', on_delete=CASCADE)
    text = models.TextField()
    created = models.DateTimeField(default=datetime.now(), db_index=True)

sampleapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class SignUpForm(forms.Form):
    username = forms.CharField(label='Choose a username',
                               min_length=3,
                               max_length=50,
                               widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    first_name = forms.CharField(label='Enter first name',
                                 max_length=50,
                                 widget=forms.TextInput(attrs={'placeholder': 'First Name (Optional)'}))
    last_name = forms.CharField(label='Enter last name',
                                max_length=50,
                                widget=forms.TextInput(attrs={'placeholder': 'Last Name (Optional)'}))
    password1 = forms.CharField(label='Enter password',
                                widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    password2 = forms.CharField(label='Confirm password',
                                widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password'}))

    def clean_username(self):
        uname = self.cleaned_data.get('username').lower()
        qset = User.objects.filter(username=uname)
        if qset.count() > 0:
            raise ValidationError("Username %s is already taken" % uname)
        return uname

    # def clean_email(self):
    #     email = self.cleaned_data.get('email').lower()
    #     qset = User.objects.filter(email=email)
    #     if qset.count() > 0:
    #         raise ValidationError("Account with email address %s exists! Please log in." % email)
    #     return email

    def clean_password2(self):
        pwd1 = self.cleaned_data.get('password1')
        pwd2 = self.cleaned_data.get('password2')

        if pwd1 and pwd2 and pwd1 != pwd2:
            raise ValidationError("Passwords do not match.")

        return pwd2

    def save(self, commit=True):
        user = User.objects.create_user(
            username=self.cleaned_data.get('username'),
            first_name=self.cleaned_data.get('first_name'),
            last_name=self.cleaned_data.get('last_name'),
            password=self.cleaned_data.get('password1')
        )
        return user

sampleapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from datetime import datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.sessions.models import Session
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.utils import timezone
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode

# from sampleapp.models import Room
from .models import Room, MusicPiece
from .tokens import account_activation_token
from .forms import SignUpForm

# Create your views here.

def index_view(request):
    template = 'sampleapp/index.html'
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('sampleapp:home'))

    context = {}
    signUpForm = SignUpForm()

    kwargs = request.session
    if kwargs:
        context['signup_errors'] = kwargs.pop('signup_errors', None)
        context['signin_error'] = kwargs.pop('signin_error', None)
        context['signin_username'] = kwargs.pop('signin_username', None)
        context['redirect_from'] = kwargs.pop('redirect_from', None)

        uname = kwargs.pop('signup_username', None)
        email = kwargs.pop('signup_email', None)
        fname = kwargs.pop('signup_fname', None)
        lname = kwargs.pop('signup_lname', None)

        if uname and email and fname and lname:
            signUpForm = SignUpForm(initial={
                'username': uname,
                'first_name': fname,
                'last_name': lname,
                'email': email,
            })

    context['signup_form'] = signUpForm

    return render(request, template, context)


def signup_view(request):
    '''
    Sign up functionality.
    :param request:
    :return:
    '''

    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            # user.is_active = False
            user.is_active = True
            user.save()
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return HttpResponseRedirect(reverse('sampleapp:home'))

            # current_site = get_current_site(request)
            #
            # subject = 'Welcome to Ting! Thanks for signing up!'
            #
            # message = render_to_string('sampleapp/activation_email.html', {
            #     'user': user,
            #     'domain': current_site.domain,
            #     'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            #     'token': account_activation_token.make_token(user),
            # })
            # # user.email_user(subject, message)
            #
            # send_mail(subject=subject,
            #           message=message,
            #           from_email=EMAIL_HOST_USER,
            #           recipient_list=[user.email,],
            #           fail_silently=False)
            # return HttpResponseRedirect(reverse('sampleapp:account_activation_sent'))
        else:
            # messages.error(request, form)
            username = form.data.get('username')
            email = form.data.get('email')
            fname = form.data.get('first_name')
            lname = form.data.get('last_name')

            request.session['signup_username'] = username
            request.session['signup_email'] = email
            request.session['signup_fname'] = fname
            request.session['signup_lname'] = lname

            for key in form.errors:
                messages.error(request, form.errors.get(key))
            return HttpResponseRedirect(reverse('sampleapp:index'))

    return HttpResponseRedirect(reverse('sampleapp:index'))


def login_view(request):
    if request.method == 'POST':
        # Correct login method.
        uname = request.POST.get('username')
        pwd = request.POST.get('pwd')

        user = authenticate(username=uname, password=pwd)

        if user is not None:
            # The redirect must be to the home page. Change this later.
            login(request, user)
            return HttpResponseRedirect(reverse('sampleapp:home'))
        else:
            # Mark the error and send it back. We're clearing out the password and keeping the username.
            request.session['signin_error'] = 'Incorrect username or password.'
            request.session['signin_username'] = uname
            request.session['redirect_from'] = 'login'
            return HttpResponseRedirect(reverse('sampleapp:index'))
    else:
        # Incorrect method of login. Might need to change this later.
        if not request.user.is_authenticated:
            return HttpResponseRedirect(reverse('sampleapp:index'))

        return HttpResponseRedirect(reverse('sampleapp:home'))


def about_view(request):
    return render(request, 'sampleapp/about.html')


@login_required(login_url='/music/login/')
def home_view(request):
    if request.method == 'POST':
        notes = request.POST.get('message')
        MusicPiece.objects.create(creator=request.user, text=notes, created=datetime.now())
        return HttpResponseRedirect(reverse('sampleapp:home'))
    else:
        form = PasswordChangeForm(user=request.user)
        active_users = get_current_users(request)

        # Get conversations
        my_conversations = []
        for obj in Room.objects.all():
            if obj.contains_user(request.user.id):
                # Sending data as a tuple.
                # The tuple will be (room name, room link)
                my_conversations.append((obj.get_room_name(request.user.id), obj.get_room_link(request.user.id)))

        # my_msgs = request.user.sent_messages.order_by('-timestamp')
        my_msgs = MusicPiece.objects.all().filter(creator=request.user).order_by('created')
        msg_data = []
        for msg in my_msgs:
            msg_data.append((msg.text, msg.created.strftime("%Y-%m-%d %H:%M:%S")))

        context = {'change_pwd_form': form,
                   'online_users': active_users,
                   'my_conversations': my_conversations,
                   'msg_data': msg_data}
        return render(request, 'sampleapp/home.html', context)


@login_required(login_url='/music/login')
def profile_view(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('sampleapp:login'))
    return render(request, 'sampleapp/profile.html', {'user': request.user})


@login_required(login_url='/music/login')
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('sampleapp:index'))


@login_required(login_url='/music/login')
def change_pwd(request):
    if request.method == 'POST':
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return HttpResponseRedirect(reverse('sampleapp:index'))
        else:
            return render(request, "sampleapp/change_pwd.html", { 'change_pwd_form': form })
    else:
        return HttpResponseRedirect(reverse('sampleapp:home'))


def account_activation_sent(request):
    return render(request, 'sampleapp/activation_sent.html')


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.profile.email_confirmed = True
        user.save()
        login(request, user)
        return HttpResponseRedirect(reverse('sampleapp:index'))
    else:
        return render(request, 'sampleapp/account_activation_invalid.html')


def get_current_users(request):
    active_sessions = Session.objects.filter(expire_date__gte=timezone.now())
    user_id_list = []
    for session in active_sessions:
        data = session.get_decoded()
        some_user = data.get('_auth_user_id', None)

        if some_user and int(some_user) != int(request.user.id):
            user_id_list.append(some_user)

    # Query all logged in users based on id list
    return User.objects.filter(id__in=user_id_list)


def chat_with(request, u):
    """
    Opens the chat window for a specific user.
    u is either 'all', or the ID of a user.
    :param request:
    :param u:
    :return:
    """
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('sampleapp:index'))

    # Can't chat with yourself
    if str(u) == str(request.user.id):
        return HttpResponseRedirect(reverse('sampleapp:error'))

    if u == 'all':
        # Global chat
        room, created = Room.objects.get_or_create(label='global')
        context = { 'chatting_with': 'Everyone' }
        return render_room(room, request, context)
    else:
        try:
            # Checking if the other user exists
            other_user = User.objects.get(id=u)

            # Get the room and render it
            room = get_room(request.user.id, u)
            chatting_with = other_user.first_name + ' ' + other_user.last_name if len(other_user.first_name) > 0 and len(other_user.last_name) > 0 else other_user.username

            context = { 'chatting_with': chatting_with }
            return render_room(room, request, context)
        except User.DoesNotExist:
            return render(request, 'sampleapp/error.html')


def error_view(request):
    return render(request, 'sampleapp/error.html')

def render_room(room, request, context):
    """
    Renders a chat room.
    :param room: Chat room object
    :param request: HTTP request object

sampleapp/templates/sampleapp/about.html
{% extends "base.html" %}

{% block head_title %}
    About || Ting
{% endblock %}

{% block content %}
    <div class="box_div">
        <h3 class="page_heading">About</h3>
        <hr>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sed blandit magna, sed laoreet nunc.
            Vivamus vel enim semper, faucibus erat ut, luctus augue. Nunc dolor sem, blandit eu varius vitae,
            tincidunt ut neque. Praesent dignissim risus congue aliquam volutpat. Nulla facilisi. Nullam
            rhoncus erat vel accumsan semper. Pellentesque habitant morbi tristique senectus et netus et
            malesuada fames ac turpis.
        </p>
    </div>
{% endblock %}

sampleapp/templates/sampleapp/account_activation_invalid.html
{% extends "base.html" %}

{% block head_title %}
    Activation link sent || Ting
{% endblock %}

{% block content %}
    <div class="box_div">
        <h3 class="box_div">Um...</h3>
        <hr>

        <p>Something went wrong with your activation link.
            Please click <a href="{% url 'sampleapp:signup' %}">here</a> to sign up again.
        </p>
    </div>
{% endblock %}

sampleapp/templates/sampleapp/activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Welcome to Ting!

Please click the link below to confirm your registration:

http://{{ domain }}{% url 'sampleapp:activate' uidb64=uid token=token %}
{% endautoescape %}

sampleapp/templates/sampleapp/activation_sent.html
{% extends "base.html" %}

{% block head_title %}
    Activation link sent || Ting
{% endblock %}

{% block content %}
    <div class="box_div">
        <h3 class="page_heading">You're nearly there.</h3>
        <hr>

        <p>
            We've sent you a confirmation email.
            Click the link in it, and you're done signing up!<br>See you soon.
        </p>
    </div>
{% endblock %}

sampleapp/templates/sampleapp/change_pwd.html
<h3 class="page_heading">Change Password</h3>
<hr>

<form method="post" action="{% url "sampleapp:change_pwd" %}">
    {% csrf_token %}
    <table class="form_table">
        {% for field in change_pwd_form %}
            <tr>
                <td>{{ field.label_tag }}</td>
                <td>{{ field }}</td>
                <td>
                    {% for error in field.errors %}
                        <p style="color: red">{{ error }}</p>
                </td>
            </tr>
            {% endfor %}
        {% endfor %}
    </table>

{#    {{ change_pwd_form }}#}

    <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent"
            type="submit">Change Password</button>
</form>

sampleapp/templates/sampleapp/error.html
{% extends "base.html" %}

{% block head_title %}
Error || Ting
{% endblock %}

{% block content %}
    <div class="box_div">
        <h3 class="page_heading">Um...</h3>
        <hr>

        <p class="piece_heading">Something went wrong. We're working on it.
            But we got you a pretty picture to make up for it. :)</p>
        <br>

        {% load static %}
        <img src="{% static 'images/wrong_small.png' %}" alt="Something went wrong.">
    </div>
{% endblock %}

sampleapp/templates/sampleapp/home.html
{% extends "base.html" %}

{% block head_title %}
    Home || Ting
{% endblock %}

{% block tab_bar %}
    <!-- Tabs -->
    <div class = "mdl-layout__tab-bar mdl-js-ripple-effect">
        <a href="#go-tab" class="mdl-layout__tab is-active" onclick="muted = false;">Go Ting!</a>
        <a href="#social-tab" class="mdl-layout__tab" onclick="muted = true;">Socialize</a>
        <a href="#profile-tab" class="mdl-layout__tab" onclick="muted = true;">Profile</a>
        {% if not user.is_anonymous %}
            <a href="#change-pwd-tab" class="mdl-layout__tab" onclick="muted = true;">Change Password</a>
        {% endif %}
    </div>
{% endblock %}

{% block content %}
    <main class="mdl-layout__content">

        <!-- Social tab -->
        <section class = "mdl-layout__tab-panel" id = "social-tab">
            <div class = "page-content box_div">
                <!-- Home -->
                {% load static %}
                {% include "sampleapp/online_users.html" %}
                <hr>

                <div class="custom_row side_by_side">
                    <div class="custom_col">
                        <h5 class="piece_heading">Your conversations</h5>
                        {% for name, link in my_conversations %}
                            <div class="one_conversation">
                                <form action="{% url 'sampleapp:chat' u=link %}">
                                <button class="mdl-button mdl-js-button mdl-js-ripple-effect"
                                        type="submit">{{ name }}</button>
                                </form>
{#                                <a href="{% url 'sampleapp:chat' u=link %}">{{ name }}</a>#}
                            </div>
                            <br>
                        {% endfor %}

                    </div>
{#                    <div class="custom_col right">#}
{#                        SoundCloud placeholder.#}
{#                    </div>#}
                </div>
            </div>
        </section>

        <!-- Profile tab -->
        <section class = "mdl-layout__tab-panel" id = "profile-tab">
            <div class = "page-content box_div">
                <!-- Profile -->
                {% load static %}
                {% include "sampleapp/profile.html" %}
            </div>
        </section>

        <!-- Go tab -->
        <section class = "mdl-layout__tab-panel is-active" id = "go-tab">
            <div class = "page-content box_div side_by_side">
{#                Go Ting placeholder#}
                <div class="mdl-grid vertical_line_right">
                    {% include "sampleapp/piano.html" %}
                </div>

                <div class="mdl-cell mdl-cell--6-col">
                    <h6 class="piece_heading">Your Music</h6>
                    <div id="music_history">
                        {% for msg, timestamp in msg_data %}
                            <div class="one_music">
                                <div class="music_heading side_by_side">
{#                                    <div class="vertical_line_right msg_name">#}
{#                                        <p class="music_name">{{ display_name }}</p>#}
{#                                    </div>#}
                                    <div class="msg_time">
                                        <p class="music_time">{{ timestamp }}</p>
                                    </div>
                                </div>
                                <hr>
                                <div class="music_text">
                                    <p class="msg_text">{{ msg }}</p>
                                </div>
                            </div>
                        {% endfor %}

                    </div>
                </div>

            </div>
        </section>

        <!-- Change password tab -->
        {% if not user.is_anonymous %}
            <section class = "mdl-layout__tab-panel" id = "change-pwd-tab">
                <div class = "page-content box_div">
                    {% load static %}
                    {% include "sampleapp/change_pwd.html" %}
                </div>
            </section>
        {% endif %}

    </main>
{% endblock %}

{% block custom_js %}
    <script>
        let notesDirectory = '{% static "notes" %}',
            hideSend = false,
            hideRecorder = false,
            muted = false,
            needSave = true;
    </script>
    <script type="text/javascript" src="{% static 'js/arm.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/piano.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/notes.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/translators/translator.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/translators/retranslator.js' %}"></script>
    <script async type="text/javascript" src="{% static 'js/keyboard.js' %}"></script>
    <script async type="text/javascript" src="{% static 'js/DOM/window_fnc.js' %}"></script>
    <script async type="text/javascript" src="{% static 'js/DOM/index.js' %}"></script>
    <script async type="text/javascript" src="{% static 'js/DOM/window_dom.js' %}"></script>

    <script type="text/javascript" src="{% static 'js/play_music.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/solo.js' %}"></script>
{% endblock %}

sampleapp/templates/sampleapp/index.html
{% extends "base.html" %}

{% block head_title %}
    Welcome || Ting
{% endblock %}

{% block tab_bar %}
    <!-- Tabs -->
    <div class = "mdl-layout__tab-bar mdl-js-ripple-effect">
        <a id="signup-tab-link" href="#signup-tab" class="mdl-layout__tab is-active" onclick="muted = true;">Sign up</a>
        <a id="signin-tab-link" href="#signin-tab" class="mdl-layout__tab" onclick="muted = true;">Sign in</a>
        <a id="tryit-tab-link" href="#tryit-tab" class="mdl-layout__tab" onclick="muted = false;">Give it a try!</a>
    </div>
{% endblock %}

{% block content %}
    <main class="mdl-layout__content">

        <!-- Sign up tab -->
        <section class = "mdl-layout__tab-panel is-active" id = "signup-tab">
            <div class = "page-content box_div">
                <!-- Sign up -->
                {% load static %}
                {% include "sampleapp/signup.html" %}
            </div>
        </section>

        <!-- Sign in tab -->
        <section class = "mdl-layout__tab-panel" id = "signin-tab">
            <div class = "page-content box_div">
                <!-- Sign in -->
                {% load static %}
                {% include "sampleapp/signin.html" %}
            </div>
        </section>

        <!-- Try it out tab -->
        <section class = "mdl-layout__tab-panel" id = "tryit-tab">
            <div class = "page-content box_div">
{#                Try it out placeholder#}
                <div class="mdl-grid">
                    {% include "sampleapp/piano.html" %}
                </div>
            </div>
        </section>

    </main>
{% endblock %}

{% if redirect_from %}
    {% block custom_js %}
        <script>
            let redirectFrom = "{{ redirect_from }}",
                hideSend = true,
                hideRecorder = true,
                muted = true;
        </script>

        {% include "sampleapp/piano_js.html" %}
    {% endblock %}
{% endif %}

sampleapp/templates/sampleapp/online_users.html
<h5 class="piece_heading">Online users</h5>
<div class="online_users_div side_by_side">
    <div id="global_chat_card" class="online_user_card">
        <a href="{% url 'sampleapp:chat' u='all' %}">
            {% load static %}
            <img class="link_image profile_pic"
                 src="{% static 'images/blank_profile_picture_small.png' %}"
                 alt="Global chat">
            <p class="online_user_text">Global Chat</p>
        </a>
    </div>

    {% for user in online_users %}
        <div class="online_user_card side_by_side">
            <a href="{% url 'sampleapp:chat' u=user.id %}">
                {% load static %}
                <img class="link_image profile_pic"
                     src="{% static 'images/blank_profile_picture_small.png' %}"
                     alt="{{ user.username }}">
                {% if user.first_name and user.first_name.strip and user.last_name and user.last_name.strip %}
                    <p class="online_user_text">{{ user.first_name }} {{ user.last_name }}</p>
                {% else %}
                    <p class="online_user_text">{{ user.username }}</p>
                {% endif %}

            </a>
        </div>
    {% endfor %}
</div>

sampleapp/templates/sampleapp/piano_js.html
{% load static %}
<script>
    let notesDirectory = '{% static "notes" %}';
</script>
<script type="text/javascript" src="{% static 'js/arm.js' %}"></script>
<script type="text/javascript" src="{% static 'js/piano.js' %}"></script>
<script type="text/javascript" src="{% static 'js/notes.js' %}"></script>
<script type="text/javascript" src="{% static 'js/translators/translator.js' %}"></script>
<script type="text/javascript" src="{% static 'js/translators/retranslator.js' %}"></script>
<script async type="text/javascript" src="{% static 'js/keyboard.js' %}"></script>
<script async type="text/javascript" src="{% static 'js/DOM/window_fnc.js' %}"></script>
<script async type="text/javascript" src="{% static 'js/DOM/index.js' %}"></script>
<script async type="text/javascript" src="{% static 'js/DOM/window_dom.js' %}"></script>
<script type="text/javascript" src="{% static 'js/play_music.js' %}"></script>

sampleapp/templates/sampleapp/profile.html
<div class="col box_div">
    <h3 class="page_heading">User Details</h3>
    <hr>

    <table class="details_table">
        <tr>
            <td><p class="bold_here">Username: </p></td>
            <td><p>{{ user.username }}</p></td>
        </tr>
        <tr>
            <td><p class="bold_here">Name: </p></td>
            <td><p>{{ user.first_name }} {{ user.last_name }}</p></td>
        </tr>
    </table>
</div>

sampleapp/templates/sampleapp/signup.html
<h3 class="page_heading">Sign up!</h3>
<hr>

{% if messages %}
    <div class="error">
        <p>The following error(s) occurred:</p>
        <ul>
            {% for foo in messages %}
                {{ foo }}
            {% endfor %}
        </ul>
    </div>
{% endif %}

<form method="post" action="{% url "sampleapp:signup" %}">

    {% csrf_token %}
    <table class="form_table">
        {% for field in signup_form %}
            <tr>
                <td>{{ field.label_tag }}</td>
                <td>{{ field }}</td>
                <td>
                    {% for err in field.errors %}
                        <p>{{ err }}</p>
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
    </table>

    <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent"
            type="submit">Sign up</button>
</form>