sampleapp/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views

from . import views

app_name = 'sampleapp'

# Basics
urlpatterns = [
    url(r'^$', views.index_view, name='index'),
    url(r'^about/$', views.about_view, name='about'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
]

# Create an account
urlpatterns += [
    url(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^signup/$', views.signup_view, name='signup'),
]

# Existing account operations
urlpatterns += [
    url(r'^change/$', views.change_pwd, name='change_pwd'),
    url(r'^home/$', views.home_view, name='home'),
    url(r'^profile/$', views.profile_view, name='profile'),
    url(r'^error/$', views.error_view, name='error'),
]

# Authentication operations
urlpatterns += [
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    # url(r'^login/$', auth_views.login, name='login'),
    # url(r'^logout/$', auth_views.logout, name='logout'),
]

# Chat operations
urlpatterns += [
    url(r'^chat/(?P<u>[a-zA-Z0-9_]+)/$', views.chat_with, name='chat'),
]

# LOGIN_URL = 'signin'
# LOGOUT_URL = 'logout'
# LOGIN_REDIRECT_URL = 'home'

website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

from sampleapp import views as sampleapp_views

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/music/')),
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('sampleapp.urls')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    # url(r'^oauth/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    # url(r'^accounts/login/$', sampleapp_views.signin_view),
]

LOGIN_URL = 'login'
LOGOUT_URL = 'logout'
LOGIN_REDIRECT_URL = '/music/home'

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" manifest="{% static 'manifest.appcache' %}">
<head>
    <meta charset="UTF-8">
    <title>{% block head_title %}{% endblock head_title %}</title>
    {% include "snippets/css.html" %}
</head>
<body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
        <header class="mdl-layout__header main_bar">
            <div class="mdl-layout__header-row">
                <span class="mdl-layout-title bar_title"
                      onclick="window.location='{% url 'sampleapp:index' %}'">
                    Ting!
                </span>
            </div>

            {% block tab_bar %}{% endblock %}
        </header>

        <div class = "mdl-layout__drawer">
            <span class="mdl-layout-title bar_title"
                  onclick="window.location='{% url 'sampleapp:index' %}'">
                Ting!
            </span>

            <nav class = "mdl-navigation">
                <div class="about_link_class mdl-navigation__link">
                    <a class="about_link_tag some_link" href="{% url 'sampleapp:about' %}">About</a>
                </div>

                {% if user.is_authenticated %}
                        <div class="logout_link_class mdl-navigation__link">
                            <a class="logout_link_tag some_link" href="{% url 'sampleapp:logout' %}">Logout</a>
                        </div>
                {% endif %}

                {% block navigation %}{% endblock %}

            </nav>
        </div>

        {% block content %}{% endblock content %}
    </div>

    {% include "snippets/js.html" %}
    {% block custom_js %}{% endblock %}
    {% if user.is_authenticated %}
        {% load static %}
        <script>
            let firstname = "{{ user.first_name }}",
                lastname = "{{ user.last_name }}";
        </script>
    {% endif %}
    <script type="text/javascript" src="{% static "js/appbar.js" %}"></script>

</body>
</html>